# Generated by Django 5.1.5 on 2025-01-17 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('pre-labelled', 'Pre-labelled'), ('labelled', 'Labelled'), ('reviewed', 'Reviewed'), ('done', 'Done')], default='uploaded', max_length=50)),
                ('s3_file_key', models.CharField(max_length=255)),
                ('s3_pre_label_key', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_label_key', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
