# Generated by Django 5.1.5 on 2025-01-18 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='inserted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
