# Generated by Django 4.2.18 on 2025-02-03 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='labelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('pre-labelled', 'Pre-labelled'), ('labelling', 'Labelling'), ('labelled', 'Labelled'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('done', 'Done')], default='uploaded', max_length=50),
        ),
    ]
