# Generated by Django 4.2.18 on 2025-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0002_annotation_labelled_by_annotation_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('pre-labelled', 'Pre-labelled'), ('in-labelling', 'In-Labelling'), ('in-review', 'In-Review'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='uploaded', max_length=50),
        ),
    ]
