# Generated by Django 4.2.19 on 2025-02-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connect', '0003_alter_annotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='labelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
